
# -*- coding: utf-8 -*-
"""硬笔书法结构检测（1.0版）.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FsalttY4p1C-DPpGlskvZF0TyKWnOouz
"""

import ipywidgets as widgets
from IPython.display import display, clear_output, Image as IPImage
from PIL import Image, ImageDraw, ImageFont # ImageFont is needed for render_character_from_ttf
import io
import cv2
import numpy as np
import matplotlib.pyplot as plt # matplotlib is needed for process_and_compare_characters and render_character_from_ttf

# --- Function Definitions (Consolidated here to ensure scope) ---

def extract_and_draw_contours(img_path, save_path, color_outer=(0,0,255), color_stroke=(0,255,0)):
    # Read the image
    img = cv2.imread(img_path)
    if img is None:
        print(f"Error: Could not load image from {img_path}")
        return False
    img_draw = img.copy()
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    # Binarize
    _, thresh = cv2.threshold(gray, 0, 255, cv2.THRESH_BINARY_INV + cv2.THRESH_OTSU)
    # Erosion to remove small noise
    kernel = np.ones((3,3), np.uint8)
    eroded = cv2.erode(thresh, kernel, iterations=1)
    # Extract all external contours (outer and stroke contours)
    contours, _ = cv2.findContours(eroded, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

    # 1. Extract and draw the outermost contour
    if len(contours) > 0:
        # Combine all contours to find the overall bounding box
        all_points = np.vstack([c for c in contours if cv2.contourArea(c) > 0])
        if all_points.size > 0:
            x, y, w, h = cv2.boundingRect(all_points)
            cv2.rectangle(img_draw, (x, y), (x+w, y+h), color_outer, 2)
        else:
            print(f"Warning: No significant contours found for outer box in {img_path}")

    # 2. Extract and draw each stroke's contour
    for cnt in contours:
        if cv2.contourArea(cnt) > 10:  # Filter out small noise
            cv2.drawContours(img_draw, [cnt], -1, color_stroke, 2)

    # Save the result
    cv2.imwrite(save_path, img_draw)
    print(f"已保存标记结果到:{save_path}")
    return True

def process_and_compare_characters(student_original_img_path, standard_original_img_path):
    # Define temporary paths for processed images
    standard_processed_path = standard_original_img_path.replace('.jpg', '_processed_contours.jpg')
    student_processed_path = student_original_img_path.replace('.jpg', '_processed_contours.jpg')

    print(f"Processing standard character from {standard_original_img_path}")
    if not extract_and_draw_contours(standard_original_img_path, standard_processed_path, color_outer=(0,0,255), color_stroke=(0,255,0)):
        print("Standard character processing failed.")
        return

    print(f"Processing student character from {student_original_img_path}")
    if not extract_and_draw_contours(student_original_img_path, student_processed_path, color_outer=(255,0,0), color_stroke=(255,255,0)):
        print("Student character processing failed.")
        return

    # Load the processed images
    standard_img = cv2.imread(standard_processed_path)
    student_img = cv2.imread(student_processed_path)

    if standard_img is None:
        print(f"Error: Could not load processed standard image {standard_processed_path}")
        return
    if student_img is None:
        print(f"Error: Could not load processed student image {student_processed_path}")
        return

    # Ensure images have the same height before stacking
    h1, w1 = standard_img.shape[:2]
    h2, w2 = student_img.shape[:2]

    if h1 != h2:
        if h1 < h2:
            standard_img = cv2.resize(standard_img, (int(w1 * (h2 / h1)), h2), interpolation=cv2.INTER_AREA)
        else:
            student_img = cv2.resize(student_img, (int(w2 * (h1 / h2)), h1), interpolation=cv2.INTER_AREA)

    # Horizontally stack the images
    combined_img = np.hstack((standard_img, student_img))

    # Display the combined image using matplotlib
    plt.figure(figsize=(15, 8))
    plt.imshow(cv2.cvtColor(combined_img, cv2.COLOR_BGR2RGB))
    plt.title('Standard Character vs. Student Handwritten Character (Processed Contours)')
    plt.axis('off')
    plt.show()

    print("Combined processed contour image displayed successfully.")

def render_character_from_ttf(character, font_path, font_size, output_size=(600, 600), output_path='/content/standard_char_from_ttf.jpg'):
    """
    Renders a single character from a TTF font file into an image.

    Args:
        character (str): The character to render.
        font_path (str): Path to the TTF font file.
        font_size (int): Font size to use.
        output_size (tuple): Desired size of the output image (width, height).
        output_path (str): Path to save the rendered image.
    """
    try:
        # 3. Create a blank white background image
        img = Image.new('RGB', output_size, color = (255, 255, 255))
        # 4. Create a drawing object
        draw = ImageDraw.Draw(img)
        # 5. Load the specified TTF font and font size
        font = ImageFont.truetype(font_path, font_size)

        # 6. Calculate character text size and position to center it
        # Using textbbox to get bounding box for precise centering
        bbox = draw.textbbox((0,0), character, font=font)
        text_width = bbox[2] - bbox[0]
        text_height = bbox[3] - bbox[1]

        # Calculate position to center the text
        x = (output_size[0] - text_width) / 2 - bbox[0]
        y = (output_size[1] - text_height) / 2 - bbox[1]

        # 7. Draw the character in black
        draw.text((x, y), character, font=font, fill=(0, 0, 0))

        # 8. Save the generated image
        img.save(output_path)
        print(f"Character '{character}' rendered from '{font_path}' and saved to: {output_path}")

        # Display the image
        plt.figure(figsize=(5, 5))
        plt.imshow(img)
        plt.title(f"Standard Character: '{character}' (from TTF)")
        plt.axis('off')
        plt.show()

    except Exception as e:
        print(f"Error rendering character: {e}")

# --- ipywidgets code ---

# 全局变量，用于存储当前处理的图像和其状态
current_image_pil = None # 当前显示的经过变换的PIL图像
original_image_pil = None # 原始上传的PIL图像，用于每次变换的基准
current_rotation_angle = 0 # 当前旋转角度
current_zoom_factor = 1.0 # 当前缩放比例

def display_image(pil_image):
    """将PIL图像转换为IPython可以显示的格式"""
    with io.BytesIO() as f:
        pil_image.save(f, format='PNG')
        display(IPImage(data=f.getvalue()))

def apply_transformations():
    """根据当前的旋转角度和缩放比例对原始图像进行变换"""
    global current_image_pil, original_image_pil, current_rotation_angle, current_zoom_factor

    if original_image_pil is None:
        return

    transformed_image = original_image_pil.copy()

    # 缩放
    if current_zoom_factor != 1.0:
        width, height = transformed_image.size
        new_width = int(width * current_zoom_factor)
        new_height = int(height * current_zoom_factor)
        # 使用Image.Resampling.LANCZOS (PIL.Image.LANCZOS) 进行高质量缩放
        transformed_image = transformed_image.resize((new_width, new_height), Image.Resampling.LANCZOS)

    # 旋转
    if current_rotation_angle != 0:
        # 使用Image.Resampling.BICUBIC (PIL.Image.BICUBIC) 进行高质量旋转，并保持透明背景（如果有）
        transformed_image = transformed_image.rotate(current_rotation_angle, expand=True, fillcolor=(255, 255, 255))

    current_image_pil = transformed_image
    with output_area:
        clear_output(wait=True)
        display_image(current_image_pil)

def upload_button_handler(change):
    global current_image_pil, original_image_pil, current_rotation_angle, current_zoom_factor
    uploaded_file = upload_button.value
    if uploaded_file:
        for filename, file_info in uploaded_file.items():
            content = file_info['content']
            # 使用PIL加载图像
            pil_image = Image.open(io.BytesIO(content))
            original_image_pil = pil_image.copy() # 保存原始图像用于重置
            current_rotation_angle = 0 # 重置旋转角度
            current_zoom_factor = 1.0 # 重置缩放因子

            # 更新滑块的值
            rotation_slider.value = 0
            zoom_slider.value = 1.0

            with output_area:
                clear_output(wait=True)
                print(f"已上传文件: {filename}")
            apply_transformations() # 应用初始变换并显示
            break # 只处理第一个上传的文件

def rotation_slider_handler(change):
    global current_rotation_angle
    current_rotation_angle = change.new
    apply_transformations()

def zoom_slider_handler(change):
    global current_zoom_factor
    current_zoom_factor = change.new
    apply_transformations()

def compare_button_handler(b):
    global current_image_pil
    if current_image_pil is None:
        with output_area:
            clear_output(wait=True)
            print("请先上传学生手写字图片！")
        return

    # 1. 保存当前调整后的学生手写字图片到临时文件
    student_char_for_comparison_path = '/content/student_char_for_comparison.jpg'
    current_image_pil.save(student_char_for_comparison_path)

    # 2. 渲染TTF标准字图像
    character_to_render = character_input.value # 从输入框获取字符
    font_file_path = '/content/standerd font.TTF'
    font_size_for_standard = standard_font_size_slider.value # 从滑块获取字体大小
    standard_char_from_ttf_path = '/content/standard_char_from_ttf.jpg'

    render_character_from_ttf(character_to_render, font_file_path, font_size=font_size_for_standard, output_size=(600, 600), output_path=standard_char_from_ttf_path)

    # 3. 调用 process_and_compare_characters 进行对比
    with output_area:
        clear_output(wait=True)
        print("正在对比标准字和学生手写字...")
    process_and_compare_characters(student_char_for_comparison_path, standard_char_from_ttf_path)

# 创建上传按钮
upload_button = widgets.FileUpload(
    accept='.jpg,.jpeg,.png',  # 接受的图片格式
    multiple=False,  # 只允许上传一个文件
    description='上传学生手写字图片'
)

# 创建旋转滑块
rotation_slider = widgets.IntSlider(
    value=0,
    min=-180,
    max=180,
    step=1,
    description='旋转角度:',
    continuous_update=True
)

# 创建缩放滑块
zoom_slider = widgets.FloatSlider(
    value=1.0,
    min=0.1,
    max=5.0, # 允许更大的缩放范围
    step=0.1,
    description='缩放比例:',
    continuous_update=True
)

# 创建标准字输入框
character_input = widgets.Text(
    value='学',
    description='标准字:',
    disabled=False
)

# 创建标准字大小滑块
standard_font_size_slider = widgets.IntSlider(
    value=200,
    min=50,
    max=500,
    step=10,
    description='标准字大小:',
    continuous_update=True
)

# 创建对比按钮
compare_button = widgets.Button(
    description='进行对比',
    disabled=False,
    button_style='info', # 'success', 'info', 'warning', 'danger' or ''
    tooltip='点击进行学生手写字与标准字的轮廓对比',
    icon='check'
)

# 输出区域用于显示上传信息和图片
output_area = widgets.Output()

# 绑定事件处理函数
upload_button.observe(upload_button_handler, names='value')
rotation_slider.observe(rotation_slider_handler, names='value')
zoom_slider.observe(zoom_slider_handler, names='value')
compare_button.on_click(compare_button_handler)

# 显示所有控件和输出区域
display(upload_button, rotation_slider, zoom_slider, character_input, standard_font_size_slider, compare_button, output_area)

"""---"""
